### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by seaz5150** [OGSR/OGSR-Engine#242]
Not sure if this is going to be of any use to you as the crash is unrecreatable, happend in X18 while shooting some muties. Feel free to close this if you can't do anything about it.
``` 
[25.09.20 22:25:54.807] ***************************[ScriptCrashHandler]**********************************
[25.09.20 22:25:54.807] stack traceback:
[25.09.20 22:25:54.807] *********************************************************************************
[25.09.20 22:25:54.808] ********************************************************************************
[25.09.20 22:25:54.808] !![LogStackTrace] Thread: [X-RAY Primary thread], ExceptionCode: [c0000005]
[25.09.20 22:25:56.242] !!Unhandled exception stack trace:
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrParticles.dll], AddrPC.Offset: [00007FFA238D4870], Fun: [PAPI::PAKillOld::Execute()] + [20 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xrParticles\particle_actions_collection.cpp-->986]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrGame.dll], AddrPC.Offset: [00007FF9DE402015], Fun: [CPHMovementControl::Calculate()] + [621 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xrGame\PHMovementControl.cpp-->163]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrGame.dll], AddrPC.Offset: [00007FF9DE400A2A], Fun: [CPHMovementControl::UpdateObjectBox()] + [566 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xrGame\PHMovementControl.cpp-->1172]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrGame.dll], AddrPC.Offset: [00007FF9DE2467AB], Fun: [CActor::UpdateCL()] + [139 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xrGame\Actor.cpp-->803]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C4E7A0], Fun: [CObjectList::SingleUpdate()] + [124 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\xr_object_list.cpp-->107]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C4EA7A], Fun: [CObjectList::Update()] + [394 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\xr_object_list.cpp-->165] + [19 byte(s)]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C4A640], Fun: [IGame_Level::OnFrame()] + [24 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\IGame_Level.cpp-->132]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrGame.dll], AddrPC.Offset: [00007FF9DE21475C], Fun: [CLevel::OnFrame()] + [224 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xrGame\Level.cpp-->415]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C79874], Fun: [CRegistrator<pureAppEnd>::Process()] + [84 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\pure.h-->86]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C78944], Fun: [CRenderDevice::FrameMove()] + [288 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\device.cpp-->420]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C78CB4], Fun: [CRenderDevice::on_idle()] + [220 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\device.cpp-->236]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C79462], Fun: [CRenderDevice::message_loop()] + [98 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\device.cpp-->325]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C78A67], Fun: [CRenderDevice::Run()] + [235 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\device.cpp-->366]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C3E1C8], Fun: [Startup()] + [284 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\x_ray.cpp-->214]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C3E53E], Fun: [WinMain_impl()] + [478 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\x_ray.cpp-->414]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C3BC4D], Fun: [WinMain()] + [73 byte(s)], File-->Line: [C:\Users\red\Desktop\OGSR-Engine-main\ogsr_engine\xr_3da\x_ray.cpp-->449]
! Module: [E:\honza\GOGGames\S.T.A.L.K.E.R. Shadow of Chernobyl\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF7E4C99332], Fun: [__scrt_common_main_seh()] + [262 byte(s)], File-->Line: [d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl-->288] + [33 byte(s)]
! Module: [C:\WINDOWS\System32\KERNEL32.DLL], AddrPC.Offset: [00007FFA2F967BD4], Fun: [BaseThreadInitThunk()] + [20 byte(s)]
! Module: [C:\WINDOWS\SYSTEM32\ntdll.dll], AddrPC.Offset: [00007FFA3190CE51], Fun: [RtlUserThreadStart()] + [33 byte(s)]
```

**Comment by seaz5150** [comment]
Sorry for log formating, not sure how else to insert it.

**Comment by KRodinn** [comment]
there were probably 3 attempts to fix it. I know about this problem, but I can’t do anything, because this muck has never been reproduced under the debugger.

**Comment by KRodinn** [comment]
Here's another variation on this problem:
```
[13.09.20 21:45:59.207]

FATAL ERROR

[error]Expression : error handler is invoked!

[error]Function : handler_base

[error]File : D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrCore\xrDebugNew.cpp

[error]Line : 416

[error]Description : pure virtual function call

[13.09.20 21:45:59.207] ***************************[ScriptCrashHandler]**********************************

[13.09.20 21:45:59.207] stack traceback:

[13.09.20 21:45:59.207] *********************************************************************************

[13.09.20 21:45:59.207] ********************************************************************************

[13.09.20 21:45:59.208] !![LogStackTrace] Thread: [X-RAY Primary thread]

[13.09.20 21:45:59.648] !!stack trace:

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrCore.dll], AddrPC.Offset: [00007FFBBA353E48], Fun: [BuildStackTrace()] + [48 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrCore\stacktrace_collector.cpp-->152]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrCore.dll], AddrPC.Offset: [00007FFBBA376EF9], Fun: [LogStackTrace()] + [73 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrCore\xrDebugNew.cpp-->58] + [13 byte(s)]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrCore.dll], AddrPC.Offset: [00007FFBBA376D33], Fun: [xrDebug::backend()] + [171 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrCore\xrDebugNew.cpp-->172]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrCore.dll], AddrPC.Offset: [00007FFBBA3779A7], Fun: [handler_base()] + [67 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrCore\xrDebugNew.cpp-->418]

! Module: [C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll], AddrPC.Offset: [00007FFBC5EE6954], Fun: [purecall()] + [20 byte(s)]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrGame.dll], AddrPC.Offset: [00007FFBA499080D], Fun: [CPHMovementControl::Calculate()] + [621 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\PHMovementControl.cpp-->163]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrGame.dll], AddrPC.Offset: [00007FFBA498F26A], Fun: [CPHMovementControl::UpdateObjectBox()] + [566 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\PHMovementControl.cpp-->1172]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrGame.dll], AddrPC.Offset: [00007FFBA47D4D5F], Fun: [CActor::UpdateCL()] + [139 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\Actor.cpp-->803]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751EAE76C], Fun: [CObjectList::SingleUpdate()] + [124 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\xr_object_list.cpp-->107]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751EAEA46], Fun: [CObjectList::Update()] + [394 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\xr_object_list.cpp-->165] + [19 byte(s)]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751EAA6B8], Fun: [IGame_Level::OnFrame()] + [24 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\IGame_Level.cpp-->132]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrGame.dll], AddrPC.Offset: [00007FFBA47A2CC0], Fun: [CLevel::OnFrame()] + [224 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xrGame\Level.cpp-->415]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751ED9710], Fun: [CRegistrator<pureAppEnd>::Process()] + [84 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\pure.h-->86]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751ED87E0], Fun: [CRenderDevice::FrameMove()] + [288 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\device.cpp-->420]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751ED8B50], Fun: [CRenderDevice::on_idle()] + [220 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\device.cpp-->236]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751ED92FE], Fun: [CRenderDevice::message_loop()] + [98 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\device.cpp-->325]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751ED8903], Fun: [CRenderDevice::Run()] + [235 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\device.cpp-->366]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751E9E1CC], Fun: [Startup()] + [284 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\x_ray.cpp-->214]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751E9E542], Fun: [WinMain_impl()] + [478 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\x_ray.cpp-->414]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751E9BC51], Fun: [WinMain()] + [73 byte(s)], File-->Line: [D:\a\OGSR-Engine\OGSR-Engine\ogsr_engine\xr_3da\x_ray.cpp-->449]

! Module: [C:\S.T.A.L.K.E.R.NS2016.OGSR\bin_x64\xrEngine.exe], AddrPC.Offset: [00007FF751EF9182], Fun: [__scrt_common_main_seh()] + [262 byte(s)], File-->Line: [D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl-->288] + [33 byte(s)]

! Module: [C:\WINDOWS\System32\KERNEL32.DLL], AddrPC.Offset: [00007FFBEF0D6FD4], Fun: [BaseThreadInitThunk()] + [20 byte(s)]

! Module: [C:\WINDOWS\SYSTEM32\ntdll.dll], AddrPC.Offset: [00007FFBF04BCEC1], Fun: [RtlUserThreadStart()] + [33 byte(s)]

[13.09.20 21:45:59.648] ********************************************************************************
```

**Comment by seaz5150** [comment]
Oh, then I got the crash 3 times in a row in X18. The virtual function call type happend twice.

**Comment by seaz5150** [comment]
Might have happend before at some point aswell, but it is rare for it to crash this many times.

**Comment by KRodinn** [comment]
@seaz5150 Test this version please: https://github.com/OGSR/OGSR-Engine/actions/runs/274801730

**Comment by seaz5150** [comment]
Alright, I will be play testing with it and will let you know if it is fixed. I also have saved a crash log from X18 with poltergeist in the files ending with control_animation_base_update and also a crash that happend when looting an NPC ending with UIDialogHolder if you want. Both of these happend only once to me so far I believe though, perhaps the poltergeist one twice in one run or something.

**Comment by seaz5150** [comment]
No, that has sadly not fixed it. You can easily reproduce the bug by going to X18 (or any small space?) and spam spawning tele poltergeists. Crashes every time at some point.

**Comment by seaz5150** [comment]
No, that has sadly not fixed it. You can easily reproduce the bug by going to X18 (or any small space?) and spam spawning tele poltergeists. Crashes every time at some point.

**Comment by Xottab-DUTY** [comment]
Are crash logs exactly the same?
Also, maybe starting a new game helps? (just for a test)

**Comment by seaz5150** [comment]
Just tried a new game to be sure and the same happens. Yes, all of the crash logs are the same every time.

**Comment by KRodinn** [comment]
> No, that has sadly not fixed it. You can easily reproduce the bug by going to X18 (or any small space?) and spam spawning tele poltergeists. Crashes every time at some point.

When I was playing, I myself caught such flights in the X-18, quite rarely, but not so much that it was not noticeable. However, when I played under the debugger, the error never showed up.(

**Comment by seaz5150** [comment]
What is the debugger? Is it a dev version of the engine? I can reproduce the bug easily.

**Comment by Xottab-DUTY** [comment]
> What is the debugger? Is it a dev version of the engine? I can reproduce the bug easily.

Simply speaking, it's a program named Visual Studio.


@KRodinn does OGSR produce minidumps?

**Comment by seaz5150** [comment]
Oh yeah, that debugger. Then I can imagine it can be hard. The mdmp files? I can send you those.

**Comment by KRodinn** [comment]
>Is it a dev version of the engine?

No.

> It has a chance of happening and if you spam poltergeists it will happen every time.

I won't be able to do this soon (((

@Xottab-DUTY yes, but my VS crashes when trying to open minidumps XD

**Comment by Xottab-DUTY** [comment]
> I can send you those.

Yes please! And with the logs too)

**Comment by seaz5150** [comment]
[crash1.zip](https://github.com/OGSR/OGSR-Engine/files/5288257/crash1.zip)

**Comment by Xottab-DUTY** [comment]
The is not the same as before my fix.

**Comment by seaz5150** [comment]
Hmm... are you sure it is not the same as the one I posted at the start?

**Comment by Xottab-DUTY** [comment]
Aaah, I just looked at your first post and the KRodinn's one with the another log...
Now I see that I've fixed one of the variations of this problem, a pure virtual function call.
But there's another one with `PAPI::PAKillOld::Execute()` in the beginning of the stack trace.

**Comment by seaz5150** [comment]
Nope, virtual function call still not fixed, but does not produce mdmp. 
[log2.zip](https://github.com/OGSR/OGSR-Engine/files/5288270/log2.zip)

**Comment by KRodinn** [comment]
@seaz5150 One more [**attempt**](https://github.com/OGSR/OGSR-Engine/actions/runs/276863335)

**Comment by seaz5150** [comment]
Yeah man, you fixed it! Great job.
